ITEM.name = "Large Briefcase"
ITEM.desc = "A large briefcase that carries a bit."
ITEM.width = 3
ITEM.height = 2
ITEM.invWidth = 4
ITEM.invHeight = 3
ITEM.permit = "misc"
ITEM.price = 60
ITEM.model = "models/props_c17/BriefCase001a.mdl"
